server:
  servlet:
    context-path: /admin

#数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://10.100.41.80:3501/TCWLZbyResource?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: TCWLZbyResource_qa
    password: LoXtEEvVm0mQrbPCeVX5Tv
    #hikari连接池
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 50
      auto-commit: true
      pool-name: RyanHikariCP
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select 1
