server:
    servlet:
        context-path: /admin

#数据库配置
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bingboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: bing2019!
        #hikari连接池
        hikari:
            minimum-idle: 5
            idle-timeout: 180000
            maximum-pool-size: 50
            auto-commit: true
            pool-name: RyanHikariCP
            max-lifetime: 180000
            connection-timeout: 30000
            connection-test-query: select 1